spring.application.name=StudentManagementSystemUsingSpringBoot

spring.datasource.url = jdbc:mysql://localhost:3306/StudentManagement_db
spring.datasource.username=root
spring.datasource.password=aayushi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = aayushijat52@gmail.com
spring.mail.password=rkuxttcwcmtllcqc

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
