spring.application.name=StudentManagementSystemUsingSpringBoot

spring.datasource.url = jdbc:mysql://localhost:3306/StudentManagement_db
spring.datasource.username=root
spring.datasource.password=aayushi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true